# Generated by LongWangClaw render_longwang_config.py.
# This file is local/private. Do not commit it.

LONGWANG_PROFILE={{sh:profileName}}
LONGWANG_OPENCLAW_ROOT={{sh:paths.openclawRoot}}
LONGWANG_WORKSPACE={{sh:paths.workspaceRoot}}
LONGWANG_SUPER8_ROOT={{sh:paths.super8Root}}
LONGWANG_TARGETS_ROOT={{sh:paths.targetsRoot}}
LONGWANG_REPORTS_ROOT={{sh:paths.reportsRoot}}
LONGWANG_RUNS_ROOT={{sh:paths.runsRoot}}

LONGWANG_PYTHON_BIN={{sh:commands.python}}
LONGWANG_BASH_BIN={{sh:commands.bash}}
LONGWANG_GIT_BIN={{sh:commands.git}}
LONGWANG_NODE_BIN={{sh:commands.node}}
LONGWANG_NPM_BIN={{sh:commands.npm}}
LONGWANG_OPENCODE_BIN={{sh:commands.opencode}}
LONGWANG_CODEX_BIN={{sh:commands.codex}}
LONGWANG_TMUX_BIN={{sh:commands.tmux}}
LONGWANG_DOCKER_BIN={{sh:commands.docker}}

LONGWANG_DEFAULT_MODEL={{sh:models.default.qualified}}
LONGWANG_OPENCODE_AGENT_MODEL={{sh:models.opencode.agentModel}}
LONGWANG_CODEX_MODEL={{sh:models.codex.model}}
LONGWANG_CODEX_REASONING_EFFORT={{sh:models.codex.reasoningEffort}}
OPENAI_API_KEY={{sh:models.providers.openai.apiKey}}

FOFA_KEY={{sh:assetSearch.fofaKey}}
HUNTER_API_KEY={{sh:assetSearch.hunterApiKey}}
SHODAN_KEY={{sh:assetSearch.shodanKey}}

LONGWANG_FEISHU_ENABLED={{sh:feishu.enabled}}
LONGWANG_FEISHU_DOMAIN={{sh:feishu.domain}}
LONGWANG_FEISHU_APP_ID={{sh:feishu.appId}}
LONGWANG_FEISHU_APP_SECRET={{sh:feishu.appSecret}}
LONGWANG_FEISHU_INTERNAL_SPACE={{sh:feishu.wiki.internalSpaceName}}
LONGWANG_FEISHU_DELIVERY_NODE_TITLE={{sh:feishu.wiki.deliveryReportNodeTitle}}

LONGWANG_REMOTE_RUNTIME_ENABLED={{sh:remoteRuntime.enabled}}
LONGWANG_REMOTE_RUNTIME_KIND={{sh:remoteRuntime.kind}}
LONGWANG_REMOTE_RUNTIME_LABEL={{sh:remoteRuntime.label}}
LONGWANG_REMOTE_RUNTIME_PROMPT={{sh:remoteRuntime.label}}
LONGWANG_REMOTE_SSH_HOST={{sh:remoteRuntime.sshHost}}
LONGWANG_REMOTE_SSH_USER={{sh:remoteRuntime.sshUser}}
LONGWANG_REMOTE_SSH_PORT={{sh:remoteRuntime.sshPort}}
LONGWANG_REMOTE_SSH_KEY_PATH={{sh:remoteRuntime.sshKeyPath}}
LONGWANG_REMOTE_RUNTIME_ROOT={{sh:remoteRuntime.runtimeRoot}}
LONGWANG_REMOTE_PUBLIC_BASE_URL={{sh:remoteRuntime.publicBaseUrl}}
LONGWANG_REMOTE_DOCKER_REGISTRY={{sh:remoteRuntime.dockerRegistryPath}}
LONGWANG_REMOTE_CLEANUP_RETAIN_HOURS={{sh:remoteRuntime.cleanupRetainHours}}
